name: dash_flags
description: A new Flutter package project.
version: 0.0.1
homepage: dash_flags

environment:
  sdk: ">=2.18.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/svgs/flags/countries/
    - assets/svgs/flags/languages/
