name: dash_flags
description: A package for displaying Countries and Languages flags.
version: 0.0.2
repository: https://github.com/moazelsawaf/dash_flags
issue_tracker: https://github.com/moazelsawaf/dash_flags/issues
screenshots:
  - description: Dash Flags Example GIF
    path: doc/assets/example_gif.gif

environment:
  sdk: ">=2.18.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  import_sorter: ^4.6.0

flutter:
  assets:
    - assets/svgs/flags/countries/
    - assets/svgs/flags/languages/
